{% set version = '0.6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xfun
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/xfun_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/xfun/xfun_{{ version }}.tar.gz
  sha256: a3afebf5fad5e5343ccf125b2956bc4574ec779231bdd071be09d33abdad7c88

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testit, parallel, rstudioapi, tinytex, mime, markdown, knitr, htmltools, base64enc, remotes, rmarkdown
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('xfun')"           # [not win]
    - "\"%R%\" -e \"library('xfun')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/yihui/xfun
  license: MIT + file LICENSE
  summary: Miscellaneous functions commonly used in other packages maintained by 'Yihui Xie'.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - bsennblad
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: xfun
# Type: Package
# Title: Miscellaneous Functions by 'Yihui Xie'
# Version: 0.6
# Authors@R: c( person("Yihui", "Xie", role = c("aut", "cre", "cph"), email = "xie@yihui.name", comment = c(ORCID = "0000-0003-0645-5666")), person("Daijiang", "Li", role = "ctb"), person("Xianying", "Tan", role = "ctb"), person() )
# Description: Miscellaneous functions commonly used in other packages maintained by 'Yihui Xie'.
# Imports: tools
# Suggests: testit, parallel, rstudioapi, tinytex, mime, markdown, knitr, htmltools, base64enc, remotes, rmarkdown
# License: MIT + file LICENSE
# URL: https://github.com/yihui/xfun
# BugReports: https://github.com/yihui/xfun/issues
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-04-02 03:57:42 UTC; yihui
# Author: Yihui Xie [aut, cre, cph] (<https://orcid.org/0000-0003-0645-5666>), Daijiang Li [ctb], Xianying Tan [ctb]
# Maintainer: Yihui Xie <xie@yihui.name>
# Repository: CRAN
# Date/Publication: 2019-04-02 05:30:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
