travis:
  secure:
    BINSTAR_TOKEN: j0iBTuq5dHF5XDcnXUhY8cDT8qGYaQlKOZSKEuFTjn+XaVnXF5rbyNPE0GCPa7NdvcreX5eO37MkJgx547BWI5lLLoA1qoBC9vhFGFnbn3NJmOSXs8ge9FL3uZZbuadQHwR6TWYRjKKJQQufnUSih2Wwj1aTcl9rny+voVNAHlYnWTgPqn1mFCkH7cgQA5HIz9ee9p0t/UVIS+GlflgOXs3htd8+iIGlndyUFKaUjbZKp14cmfYmkc5DQrCxTBWmvB+bHH8V3UWCqkYIvneSgQAD5VPN+Sq//RwFFvLqf1I3W3Jqs4H8Ihwuqr6iBYaqUl8POs1W7gno6YIz5tIPnj76vvbym5uOh1DgvixwYiefAHT9i+SfTLAtZtv/VkA0RSXAl6G9aiRaCyAyDt4o2J5UwIbijjzaxxt3TN0cKCggRxWAN4TzetVWuUDaSjwQh4y5v93HcgWl5ZL8Pwds+WyHgt/360MHdZVZuNbIHUcYxIZgt9Yk+2NrjEEIGkrCokQ/iwdZnMqc7H+E3d+/YsYb4YB7uRyimPT7IP0HJiP735WJPbQdRFQ00ObvhLiZB++W6BuBCkoO7rQWEv+EllExYiJXiS/vVsTU/cnbt9qe5NYUrq4H9aJGnfBcs4GWe7ppYmYyqdtF4Tcp89WBjyNzpoY4OLcNBAUOJyZ60EE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
